name: flutter_starter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

  shared_preferences: ^0.5.10
  material_design_icons_flutter: 4.0.5345

  firebase_core: ^0.5.0
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.11

  dartz: ^0.9.1
  equatable: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/locale/translations/en.json
    - lib/locale/translations/tr.json

